project_name: halloween
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates: [ "ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-amd64" ]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/dirien/{{ .ProjectName }}
  - image_templates: [ "ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-arm64" ]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/dirien/{{ .ProjectName }}

docker_manifests:
  - name_template: 'ghcr.io/dirien/halloween:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/dirien/halloween:{{ .Version }}-amd64'
      - 'ghcr.io/dirien/halloween:{{ .Version }}-arm64'
  - name_template: 'ghcr.io/dirien/halloween:latest'
    image_templates:
      - 'ghcr.io/dirien/halloween:{{ .Version }}-amd64'
      - 'ghcr.io/dirien/halloween:{{ .Version }}-arm64'